const Images = {
  nophoto: require('../assets/images/nophoto.jpeg'),
  logo: require('../assets/images/logo.png'),
  loaderlogo: require('../assets/images/loaderlogo.gif'),
  ic_11: require('../assets/images/ic_11.png'),
  applogo1: require('../assets/images/applogo1.png'),
  logo_white: require('../assets/images/logo_white.png'),
  ic_tooltip: require('../assets/images/ic_tooltip.png'),
  back_auth: require('../assets/images/back_auth.png'),
  ic_background: require('../assets/images/ic_background.png'),
  nodata: require('../assets/images/nodata.png'),

  ic_scan_p: require('../assets/images/ic_scan_p.png'),
  ic_lottery: require('../assets/images/ic_lottery.jpeg'),
  ic_cal: require('../assets/images/ic_cal.png'),

  healthyfood: require('../assets/images/healthyfood.png'),
  placeholder4: require('../assets/images/placeholder4.png'),
  placeholder3: require('../assets/images/placeholder3.png'),
  placeholder5: require('../assets/images/placeholder5.png'),
  ic_placeholder: require('../assets/images/ic_placeholder.png'),
  ic_all: require('../assets/images/ic_all.png'),
  ic_placeholder1: require('../assets/images/ic_placeholder1.png'),
  s_r1: require('../assets/images/s_r1.png'),

  ic_rr1: require('../assets/images/ic_rr1.png'),
  ic_rr2: require('../assets/images/ic_rr2.png'),
  ic_rr3: require('../assets/images/ic_rr3.png'),

  ic_s1: require('../assets/images/ic_s1.png'),
  ic_s2: require('../assets/images/ic_s2.png'),
  ic_s3: require('../assets/images/ic_s3.png'),
  ic_s4: require('../assets/images/ic_s4.png'),
  ic_s5: require('../assets/images/ic_s5.png'),
  ic_s6: require('../assets/images/ic_s6.png'),
  ic_s7: require('../assets/images/ic_s7.png'),
  ic_s8: require('../assets/images/ic_s8.png'),
  ic_s9: require('../assets/images/ic_s9.png'),
  ic_s10: require('../assets/images/ic_s10.png'),
  ic_s11: require('../assets/images/ic_s11.png'),

  ic_w1: require('../assets/images/ic_w1.png'),
  ic_w2: require('../assets/images/ic_w2.png'),
  ic_w3: require('../assets/images/ic_w3.png'),
  ic_w4: require('../assets/images/ic_w4.png'),

  ic_date: require('../assets/images/ic_date.png'),
  ic_r1: require('../assets/images/ic_r1.png'),
  ic_r2: require('../assets/images/ic_r2.png'),
  ic_r3: require('../assets/images/ic_r3.png'),
  ic_type: require('../assets/images/ic_type.png'),
  ic_r4: require('../assets/images/ic_r4.png'),

  list: require('../assets/images/list.png'),
  ic_add: require('../assets/images/ic_add.png'),
  ic_remove: require('../assets/images/ic_remove.png'),
  ic_ar_right: require('../assets/images/ic_ar_right.png'),
  ic_black_img: require('../assets/images/ic_black_img.png'),
  ic_border: require('../assets/images/ic_border.png'),
  ic_close: require('../assets/images/ic_close.png'),
  ic_cup: require('../assets/images/ic_cup.png'),
  ic_deals: require('../assets/images/ic_deals.png'),
  ic_distance: require('../assets/images/ic_distance.png'),
  ic_giftcard: require('../assets/images/ic_giftcard.png'),
  ic_home: require('../assets/images/ic_home.png'),
  ic_grid: require('../assets/images/ic_grid.png'),
  ic_wlt: require('../assets/images/ic_wlt.png'),
  ic_info: require('../assets/images/ic_info.png'),
  ic_settings: require('../assets/images/ic_settings.png'),
  ic_map: require('../assets/images/ic_map.png'),
  ic_marketplace: require('../assets/images/ic_marketplace.png'),
  ic_nfc_scan: require('../assets/images/ic_nfc_scan.png'),
  ic_wallet: require('../assets/images/ic_wallet.png'),
  ic_qr_code: require('../assets/images/ic_qr_code.png'),
  ic_reward: require('../assets/images/ic_reward.png'),
  ic_scan: require('../assets/images/ic_scan.png'),
  ic_upload: require('../assets/images/ic_upload.png'),
  ic_user_white: require('../assets/images/ic_user_white.png'),
  ic_user: require('../assets/images/ic_user.png'),
  ic_star: require('../assets/images/ic_star.png'),
  ic_barcode: require('../assets/images/ic_barcode.png'),
  ic_copy: require('../assets/images/ic_copy.png'),
  ic_send_gift: require('../assets/images/ic_send_gift.png'),

  ic_b1: require('../assets/images/ic_b1.png'),
  ic_b2: require('../assets/images/ic_b2.png'),
  ic_b3: require('../assets/images/ic_b3.png'),
  ic_b4: require('../assets/images/ic_b4.png'),
  ic_b5: require('../assets/images/ic_b5.png'),
  ic_b6: require('../assets/images/ic_b6.png'),
  ic_b7: require('../assets/images/ic_b7.png'),
  ic_b8: require('../assets/images/ic_b8.png'),

  ic_map_l: require('../assets/images/ic_map_l.png'),
  ic_address: require('../assets/images/ic_address.png'),

  ic_b8: require('../assets/images/ic_b8.png'),
  ic_b8: require('../assets/images/ic_b8.png'),
  ic_b8: require('../assets/images/ic_b8.png'),

  or_1: require('../assets/images/or_1.png'),
  or_2: require('../assets/images/or_2.png'),
  or_3: require('../assets/images/or_3.png'),
  or_4: require('../assets/images/or_4.png'),
  or_5: require('../assets/images/or_5.png'),
  or_6: require('../assets/images/or_6.png'),

  at1: require('../assets/images/at1.png'),
  at2: require('../assets/images/at2.png'),
  at3: require('../assets/images/at3.png'),
  at4: require('../assets/images/at4.png'),
  ic_buss: require('../assets/images/ic_buss.png'),
  ic_bb: require('../assets/images/ic_bb.png'),

  ic_delete: require('../assets/images/ic_delete.png'),

  ic_delete_img: require('../assets/images/ic_delete_img.jpeg'),

  icd1: require('../assets/images/icd1.jpeg'),
  icd2: require('../assets/images/icd2.jpeg'),
  icd3: require('../assets/images/icd3.jpeg'),
  icd4: require('../assets/images/icd4.jpeg'),
  ic_op: require('../assets/images/ic_op.png'),
  email: require('../assets/images/email.png'),
  phone: require('../assets/images/phone.png'),


};
export default Images;
